# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('state', models.CharField(default='1', editable=False, max_length=1)),
            ],
            options={
                'db_table': 'LANGUAGES',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('embed_code', models.CharField(max_length=255)),
                ('state', models.CharField(default='1', editable=False, max_length=1)),
                ('languages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Language')),
                ('movies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'db_table': 'SERVERS_MOVIES',
            },
        ),
    ]
