# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_servers_id'),
        ('servers', '0002_auto_20171227_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AlterModelTable(
            name='server',
            table='SERVERS_MOVIES',
        ),
    ]
