# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('birthdate', models.DateField()),
                ('state', models.CharField(default='1', editable=False, max_length=1)),
            ],
            options={
                'db_table': 'ACTORS',
            },
        ),
        migrations.CreateModel(
            name='Actor_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor')),
            ],
            options={
                'db_table': 'ACTORS_MOVIES',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255)),
                ('state', models.CharField(default='1', editable=False, max_length=1)),
            ],
            options={
                'db_table': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('duration', models.TimeField()),
                ('productora', models.CharField(max_length=500)),
                ('path', models.ImageField(upload_to='imagenes/')),
                ('director', models.CharField(max_length=500)),
                ('state', models.CharField(default='1', editable=False, max_length=1)),
                ('actors', models.ManyToManyField(through='movies.Actor_Movie', to='movies.Actor')),
                ('categories_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Categorie')),
            ],
            options={
                'db_table': 'MOVIES',
            },
        ),
        migrations.AddField(
            model_name='actor_movie',
            name='movies_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
