# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_servers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='servers_id',
        ),
    ]
