# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180102_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
