# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
