# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
